---
- name: Dump assetic assets.
  shell: cd {{symfony_current_release_dir}} && {{symfony_project_php_path}} {{symfony_console}} assetic:dump --env={{symfony_project_env}} {{symfony_project_console_opts}}
  when: composer_content.stdout.find('assetic-bundle') != -1

- name: Symlink/install assets.
  shell: cd {{symfony_current_release_dir}} && {{symfony_project_php_path}} {{symfony_console}} assets:install --symlink --env={{symfony_project_env}} {{symfony_project_console_opts}}
  when: symfony_project_symlink_assets == True
