---
# tasks file for symfony2
- include: 00-facts.yml

- name: Create/prepare necessary directories for release and shared data.
  file: state=directory path={{item.path}}
  with_items:
    - { path: "{{symfony_current_release_dir}}" }

- name: Pull sources from the repository.
  git: repo={{symfony_project_repo}} dest={{symfony_current_release_dir}} version={{symfony_project_branch}} accept_hostkey=yes depth={{symfony_project_git_clone_depth}}

# will be replaced with symlink
- name: Ensure logs directory is not present.
  file: state=absent path="{{symfony_current_release_dir}}/source/app/logs"

# read project's composer.json and store output
- name: Read composer.json
  shell: cat {{symfony_current_release_dir}}/source/composer.json
  register: composer_content

- include: "{{ symfony_project_post_folder_creation_tasks | default('empty.yml') }}"

- include: 10-config.yml

- include: 20-composer.yml

- include: "{{ symfony_project_pre_cache_warmup_tasks | default('empty.yml') }}"

- include: 30-cache.yml

- include: 40-assets.yml

- include: 50-migrations.yml

- name: create release file
  copy: content="{{symfony_current_release}}" dest="{{symfony_current_release_dir}}/RELEASE" mode=644

- include: "{{ symfony_project_pre_live_switch_tasks | default('empty.yml') }}"

- name: Create symlink for release.
  file: state=link src="{{symfony_current_release_dir}}" path="{{symfony_project_root}}/current"

- include: "{{ symfony_project_post_live_switch_tasks | default('empty.yml') }}"

